language: csharp
matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    sudo: required
    dotnet: 2.0.0
    mono: none
  - os: osx
    osx_image: xcode8.3 # macOS 10.12
    dotnet: 2.0.0
    mono: none
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5
install:
  - ulimit -n 1024
  - nvm install 6.11.5
  - nvm use 6.11.5
  - npm install yarn bower webpack coffee-script cordova grunt-cli gulp-cli typescript jspm less node-sass -g
  - dotnet restore
branches:  
  only:
    - master
script:  
  - ulimit -n 1024
  - dotnet build
  - dotnet test

