language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
env:  
  - CLI_VERSION=latest
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5
os:  
  - linux
  - osx
osx_image: xcode7.1  
branches:  
  only:
    - master
script:  
  - dotnet restore
  - dotnet build
  - dotnet test

