language: csharp
matrix:
  allow_failures:
  - os: osx
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    sudo: required
    dotnet: 2.0.0
    mono: none
    before_install:
      - curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
        - unzip consul.zip
        - mkdir -p ~/bin
        - mv consul ~/bin
        - export PATH="~/bin:$PATH"
  - os: osx
    osx_image: xcode8.3 # macOS 10.12
    dotnet: 2.0.0
    mono: none
    before_install:
      - curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_darwin_amd64.zip
        - unzip consul.zip
        - mkdir -p ~/bin
        - mv consul ~/bin
        - export PATH="~/bin:$PATH"
#  include:
#   - language: python
#      python: 2.7
#      before_script:
#        - cd backend/tests
#      script:
#        - python -m unittest discover
#    - language: android
#      jdk: oraclejdk8
#      android:
#        components:
#          - tools
#          - android-25
#          - build-tools-25.0.3
#      before_script:
#        - cd android/AppName
#      script:
#        - ./gradlew build connectedCheck
#    - language: objective-c
#      os: osx
#      osx_image: xcode8.3
#      before_script:
#        - cd ios/AppName
#      script:
#        - xcodebuild -workspace AppName.xcworkspace -scheme AppName
#          -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' build test    
#addons:
  #apt:
    #sources:
    #- sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
    #  key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    #packages:
    #- dotnet-hostfxr-1.0.1
    #- dotnet-sharedframework-microsoft.netcore.app-1.0.5
install:
  - ulimit -n 1024
  - nvm install 6.11.5
  - nvm use 6.11.5
  - npm install yarn bower webpack coffee-script cordova grunt-cli gulp-cli typescript jspm less node-sass -g
branches:  
  only:
    - master
env:
  - CONSUL_VERSION=1.0.0
  - NODE_ENV=testing
  - GOMAXPROCS=4    
script:  
  - ulimit -n 1024
  - dotnet restore
  - dotnet build
# - dotnet build -f netcoreapp2.0
# - xbuild /m test.build
  - dotnet msbuild /m test.build
# - dotnet msbuild /p:TargetFramework=netcoreapp2.0
#  - dotnet publish
